name: gpic-caption-concepts
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - tqdm
  - huggingface_hub
  - spacy
  - spacy-model-en_core_web_sm
  - spacy-model-en_core_web_md
  - spacy-model-en_core_web_lg
  - spacy-model-en_core_web_trf
  - pip:
      - cupy-cuda13x
